spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql : true
  h2:
    console:
      enabled: true
  jackson:
    default-property-inclusion: non_null
  output:
    ansi:
      enabled: always
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org:
      hibernate:
#        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace